JavaScript Capstone HollyFlix Website
sumairq/hollyflix-capstone pull request #38
Opened 2022-02-19 20:27 UTC by sumairq

# Information about the Hollyflix project!
## **Interfaces**
- ### We build these interfaces:
  - The *home page*.
  - The *comments popup*.
  - The *reservations popup*.
- ### We follow the layout of the wireframes provided. We personalize the rest of the design including colors, typographies, spacings, etc.
- ### Home page
  - When the page loads, the webapp retrieves data from:
    - The selected API and shows the list of items on screen.
    - The Involvement API to show the item likes.
  - ### Our page make only 2 requests:
    - One to the base API.
    - And **one** to the Involvement API.
  - ### When the user clicks on the Like button of an item, the interaction is recorded in the Involvement API and the screen is updated.
  - When the user clicks on the "Comments" button, the Comments popup appears.
  - When the user clicks on the "Reservations" button, the Reservations popup appears (only for the groups of 3 students).
  - Home page header and navigation similar to the given mockup.
  - Home page footer similar to the given mockup.
- ### Comments popup
  - When the popup loads, the webapp retrieves data from:
    - The selected API and shows details about the selected item.
    - The Involvement API to show the item comments.
  - When the user clicks on the "Comment" button, the data is recorded in the Involvement API and the screen is updated.
- ### Reservations popup.
  - When the popup loads, the webapp retrieves data from:
    - The selected API and shows details about the selected item.
    - The Involvement API to show the item reservations.
  - When the user clicks on the "Reserve" button, the data is recorded in the Involvement API and the screen is updated.

## **Counters**
We have counters in all the interfaces that show:
- The number of items (home).
- The number of comments (comments popup).
- The number of reservations (reservations popup) - only for the groups of 3 students..

## **Technical set up**
- We set up the repository on GitHub and use Gitflow.
- We set webpack.
- We set a JavaScript testing library (Jest).
<img width="100%" src="https://media4.giphy.com/media/bmbEMk3KQrsZaWzhuT/giphy.gif"/>

2022-02-19 21:05 UTC, Hamzaoutdoors requested changes
Hey team, I am **Hamza** your reviewer for this PR 😸 

_You did a great job, I really enjoyed surfing on your fancy website 😃_ 

## To Highlight
✔️ The repo looks professional
✔️ There are no linter errors
✔️ You have a descriptive README
✔️ Wonderful UI design and good choice of theme🥇 
✔️ Great Job building your project to be modular 
✔️ The Unit Tests are passed 👍🏼 

_I can see you're really putting effort to become a world-class software developer 👍_

There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Required Changes ♻️

- [REQUIRED]

Please add a link to the API used in this project in the `Acknowledgments` section of the README


_See the inline comments below for more required changes 😃_  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ OPTIONAL] 
I think it will be better to don't let a broken link in your REAMDE. Currently, your Live Demo link is broken. I think it will be better if you can deploy your project, So the user can have an idea about your fancy project (I suggest that you can use [`gh-pages`](https://survivejs.com/webpack/techniques/deploying/) for this purpose 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 21:05 UTC, Hamzaoutdoors commented on src/modules/fetchMovies.js
> +    .then((data) => {
- [ ] Fair effort on using the `async await` promise syntactic sugar. However, you're mixing two syntaxes here, and the `async` keyword in this context is redundant. May we please remove the `.then` and stick to the `async await` format.

2022-02-19 22:05 UTC, Gambit142 requested changes
Hello team 👋 ,

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Kindly check the comments under the review._

## Optional changes

- [ ] I noticed that your page doesn't scroll down nor do your reservation and comments popup window. I do not know if it is my system but it would be nice to look into it as the other reviewer made no mention of it. 🙏 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-19 22:05 UTC, Gambit142 commented on README.md
- [x] (Optional) It is wonderful that the team decided to implement the optional change suggested by the other reviewer. It would be nice to do `npm run build` before deploying to `gh-pages`. That way, your dist folder would have the updated changes. The reason for this suggestion is that your page does not scroll down on the desktop version when opened with this link and `webpack server`

2022-02-19 22:05 UTC, Gambit142 commented on README.md
> +- For adding the Comment, Reservation, like functionality Microverse's Involvement API is used.
- [x] I acknowledge your effort to implement all the changes suggested by the other reviewer. However, the team did not attach the URL. Even though I can see the name of the API used, it would be better if I can click a link and be directed straight to the page. To include a link in your `README.md` file, you can either paste the link directly or do this:

```
[text](url)
```

2022-02-19 22:05 UTC, Gambit142 commented on src/modules/fetchMovies.js
> +    .then((data) => {
- [x] Kindly implement the suggestion made by the first code reviewer for this line. There is no need to have double asynchronous Syntactic sugar. All you have to do is await the response like this:

```
const data = await response.text()
```

2022-02-20 00:11 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @sumairq 👋🏻, 

Good job making the requested changes 💪🏻!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💪🏻

✅ No linter errors.
✅ You used correct Github Flow.
✅ Professional README.
✅ Used webpack to bundle JavaScript.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-20 00:13 UTC, merged